name: Build repo

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Get docker image and compile face
        run: |
          docker run --rm                          \
            "--volume=`pwd`:/project"              \
            --workdir /project                     \
            ddls/esp32_platformio_compiler:latest  \
            /bin/bash -c                           \
            "pio run -e debug"
      - name: Upload face binary artifact
        uses: actions/upload-artifact@v3
        with:
          name: Watchy-Screen-Face
          path: .pio/build/debug/firmware.bin
