name: workflow test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: install platformio
#          apt-get update && apt-get install -y \
#          git \
#          python3-pip \
#          && rm -rf /var/lib/apt/lists/* \
#          && apt-get clean \
#          && pip3 install --no-cache-dir -U platformio \
#          && pio platform install espressif32 --with-package=framework-arduinoespressif32 --with-package=tool-esptoolpy --with-package=toolchain-xtensa32 \
#          && pio system prune --force
        run: |
          apt-get install -y git
      - name: compile firmware
        run: |
          pio run -e debug
      - name: Upload face binary artifact
        uses: actions/upload-artifact@v3
        with:
          name: Watchy-Screen-Face
          path: .pio/build/debug/firmware.bin
